import '../styles/global.css';
import Header from "../components/header/Header";

export const metadata = {
  title: "The New York Times | Best Seller",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
